version: "2"
services:
    node:
        build: .
        container_name: codeceptjs
        volumes:
            - ./:/data:cached
        working_dir: "/data"
        links:
            - selenium-hub

    selenium-hub:
        container_name: selenium-hub
        image: selenium/hub
        links:
            - selenium-node-chrome-1
            - selenium-node-chrome-2
        ports:
            - "4444:4444"

    selenium-node-chrome-1:
        container_name: selenium-node-chrome-1
        image: selenium/node-chrome-debug
        environment:
            HUB_HOST: selenium-hub
        ports:
            - "59001:5900"

    selenium-node-chrome-2:
        container_name: selenium-node-chrome-2
        image: selenium/node-chrome-debug
        environment:
            HUB_HOST: selenium-hub
        ports:
            - "59002:5900"